### ISSUE TITLE
ZAP 2.4.0 Compatibility 

### ISSUE THREAD

**Issue by compfaculty** [h3xstream/http-script-generator#17]
Hello! 
Your plugin is great, but i can't run it with new  ZAP 2.4.0. (Linux). What the reason?

**Comment by h3xstream** [comment]
I will need some information (error message or stack trace).

If you don't have any error message, start ZAP this way.
{{{
cd ZAP_DIRECTORY
java -jar zap.jar
}}}
You will probably see an error in the printed output.

Alternatively, you can check `$HOME/OWASP ZAP/zap.log` for potential error messages.

**Comment by compfaculty** [comment]
I can't see any java exceptions in console, but  i have popup window
![issue](https://cloud.githubusercontent.com/assets/1645749/8419123/1afcf76c-1ec0-11e5-8ea7-450316d5ccd5.png)

**Comment by h3xstream** [comment]
Than this is most likely a bug in ZAP itself.
The plugin was started with [ZAP api 2.2.2](https://github.com/h3xstream/http-script-generator/blob/master/scriptgen-zap-plugin/src/main/resources/ZapAddOn.xml#L16) (reason for the requirement).
The metadata file was working in 2.2 and 2.3 ...

Please, ask the meaning of this error on the [ZAP mailing list](https://groups.google.com/forum/#!forum/zaproxy-users).

**Comment by vskram21** [comment]
Hi, 
It seems like ZAP has disabled loading plugin thats supports before 2.4. I guess this might be the cause for this issue - https://github.com/zaproxy/zaproxy/blob/8b848cd8bfdf6f3d4937d04c60a9dd81faec3fb6/test/resources/org/zaproxy/zap/control/ZapVersions-deps.xml

@compfaculty : Could you please provide the details of the ZAP version which you have installed.

**Comment by h3xstream** [comment]
Issue move to ZAP project : https://github.com/zaproxy/zaproxy/issues/1705

**Comment by h3xstream** [comment]
The extension is now working again in ZAP tested in 2.4.3.
Release will come soon.
