### ISSUE TITLE
Add to the ZAP Marketplace

### ISSUE THREAD

**Issue by psiinon** [h3xstream/http-script-generator#19]
Would you be interested in publishing this on the ZAP Marketplace?
That would allow ZAP users to download and install it from within ZAP :)

**Comment by h3xstream** [comment]
Yes and no. I just don't want to integrate in all my plugins in [single repo](https://github.com/zaproxy/zap-extensions).
For those reasons: stability (automate build/test breaking), integrity (see contributors), productivity (commit log pollution, unwanted notification).

**Comment by psiinon** [comment]
You dont need use our repo, you can keep using your own.
All we'll do is host the .zap file - you keep control of your code.
We'll need to work out how to generate and update it, but we have some automation that can help.

**Comment by h3xstream** [comment]
I can drop the zap files on each release. The build is automated to generate a working package for ZAP.
