### ISSUE TITLE
7407:03 ERROR: Unexpected error while building the request entity

### ISSUE THREAD

**Issue by alias1** [h3xstream/http-script-generator#23]
```1480390159738	Extender	Reissue Request Scripter: 7407:03 ERROR: Unexpected error while building the request entity.1```

**Comment by h3xstream** [comment]
@alias1 Can you provide the request that is causing problem?

I am expecting that you are right-click on **one request** and the dialog does not appear.

**Comment by alias1** [comment]
This seems to be the type of request doing it, redacted a bunch of it, but hopefully it still helps track it down.

```
POST /foo/bar/bar HTTP/1.1
Host: hvams.tmr.qld.gov.au
Connection: close
Content-Length: 272
Cache-Control: max-age=0
Origin: https://example.com
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer: https://example.com/foo/bar/bar
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8
Cookie: gsScrollPos=; ASP.NET_SessionId=sessionid AWSELB=loadbalancertoken; __RequestVerificationToken_L2h2YW1z0=my-token-here; .AspNet.ApplicationCookie=foo-bar-baz

DropDownList=112&SearchFlag=1&Prompt=Select+from+list+...&AD_81=10&AD_82=112&AD_83=20%2F10%2F2015&State=ABC&Language=en-us&DeviceType=Laptop&UserType=11111&PageName=FooPage&ViewName=BarView&PermitType=0&ButtonName=&SysMsgUrl=%2Ffoo%2bar%2Fbaz
```

**Comment by h3xstream** [comment]
On my side I get this.

```python
import requests

session = requests.Session()

paramsPost = {"AD_81":"10","AD_82":"112","PermitType":"0","AD_83":"20/10/2015","SearchFlag":"1","PageName":"FooPage","ViewName":"BarView","SysMsgUrl":"/foo+ar/baz","DeviceType":"Laptop","ButtonName":"","Language":"en-us","State":"ABC","DropDownList":"112","Prompt":"Select from list ...","UserType":"11111"}
headers = {"Origin":"https://example.com","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","Cache-Control":"max-age=0","Upgrade-Insecure-Requests":"1","Connection":"close","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36","Referer":"https://example.com/foo/bar/bar","Accept-Encoding":"gzip, deflate, br","Accept-Language":"en-US,en;q=0.8","Content-Type":"application/x-www-form-urlencoded"}
cookies = {".AspNet.ApplicationCookie":"foo-bar-baz","gsScrollPos":"","ASP.NET_SessionId":"sessionid AWSELB=loadbalancertoken","__RequestVerificationToken_L2h2YW1z0":"my-token-here"}
response = session.post("http://perdu.com/foo/bar/bar", data=paramsPost, headers=headers, cookies=cookies)

print("Status code:   %i" % response.status_code)
print("Response body: %s" % response.content)
```

Can you test with this version of the plugin (my latest build) ?

[scriptgen-burp-plugin-5.jar.zip](https://github.com/h3xstream/http-script-generator/files/646576/scriptgen-burp-plugin-5.jar.zip)

**Comment by h3xstream** [comment]
The previous commit is actually unrelated to this issue.
(This issue was not reproduce yet.)

**Comment by alias1** [comment]
Was loading this from the bapp store and it doesn't even seem to be a thing I can add that way anymore (and my local copy has vanished). Is there any plans for it to go back there? I tend not to use plugins I install seperately.

Loading your above attached file.. unable to get the issue copy/pasting the above into repeater. And going back to my old burp-state file, not sure which request it was exactly, so unable to reproduce (tried a few that I thought it might have been)

So for now, I suppose treat this as unconfirmed and close. If I see it again I will comment to open back up, and remember which request it was for!

**Comment by h3xstream** [comment]
It was likely fix and not release to the BappStore.

Let me know if the bug comes back.
