### ISSUE TITLE
Cert name errors for Perl (LWP)

### ISSUE THREAD

**Issue by mavensecurity** [h3xstream/http-script-generator#6]
Consider ignoring certificate errors, as test environment sometimes use a certificate from production which does not match the dev server name.

Add this line to any Perl (LWP):
BEGIN { $ENV{PERL_LWP_SSL_VERIFY_HOSTNAME} = 0 }

**Comment by h3xstream** [comment]
The functionality was implemented .. I will notify you when a build version is available.
